name: schedule_watch
description: ...
version: 0.0.3
publish_to: none

resolution: workspace

flutter:
  uses-material-design: true

environment:
  flutter: ^3.38.5
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  schedule_shared:
    path: ../schedule_shared
  dio: ^5.9.0
  intl: ^0.20.2
  wear_os_plugin: ^0.3.0
  shared_preferences: ^2.5.5
  watch_connectivity: ^0.2.10
  riverpod: ^3.2.1
  riverpod_devtools: ^0.4.4
  flutter_riverpod: ^3.3.1
  workmanager: ^0.10.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  test: ^1.26.2
