name: schedule
description: "Application gets schedule and homework from 'My School' service"
repository: https://github.com/Lynx20wz/schedule
publish_to: none

version: 0.1.0

flutter:
  uses-material-design: true

environment:
  flutter: ^3.38.5
  sdk: ^3.10.0

workspace:
  - packages/schedule_watch_app
  - packages/schedule_phone_app

dependencies:
  flutter:
    sdk: flutter
  watch_connectivity: ^0.2.6
  shared_preferences: ^2.5.4

dev_dependencies:
  lints: ^6.0.0
