name: schedule
description: "Application gets schedule and homework from 'My School' service"
repository: https://github.com/Lynx20wz/schedule
publish_to: none

version: 0.1.0

flutter:
  uses-material-design: true

environment:
  flutter: ^3.47.4
  sdk: ^3.13.3

workspace:
  - packages/schedule_shared
  - packages/schedule_phone
  - packages/schedule_watch

dependencies:
  flutter:
    sdk: flutter
  watch_connectivity: ^0.2.6
  shared_preferences: ^2.5.4

dev_dependencies:
  import_sorter: ^4.6.0
  lints: ^6.0.0
